//
//	GarbageCollector.cpp
//	Good Neighbours
//
//	Created by Diego Revilla on 10/12/21
//	Copyright © 2021 Diego Revilla. All Rights reserved
//

#include <Shared.h>

namespace Engine {
	namespace {
		static PageAllocator<GameObject> s_objalloc;
	}

	// ------------------------------------------------------------------------
	/*! GO Garbage Collection
	*
	*   Collects the Garbage generated by the Game Object System
	*/ //--------------------------------------------------------------------
	void GCollector::GOGarbageCollection() {
		static PageAllocator<Component> compalloc;

		for (auto& x : mToRemoveComps) {
			x->Destroy();
			x->GetOwner()->mComponents.remove(x);
			compalloc.destroy(x);
			compalloc.deallocate(x);
		}

		for (auto& x : mToRemoveChilds) {
			x->Destroy();
			x->GetParent()->mChilds.remove(x);
			s_objalloc.destroy(x);
			s_objalloc.deallocate(x);
		}

		for (auto& x : mToRemoveObjs) {
			x->Destroy();
			auto& temp_ = GWorld->GetScene()->mObjectList;
			GWorld->GetScene()->mObjectList.remove(x);
			s_objalloc.destroy(x);
			s_objalloc.deallocate(x);
		}

		mToRemoveComps.clear();
		mToRemoveChilds.clear();
		mToRemoveObjs.clear();
	}

	// ------------------------------------------------------------------------
	/*! Add Component To Remove
	*
	*   Removes a Component
	*/ //--------------------------------------------------------------------
	void GCollector::AddComponentToRemove(Component* comp) {
		mToRemoveComps.insert(comp);
	}

	// ------------------------------------------------------------------------
	/*! Add Child to Remove
	*
	*   Removes a Child
	*/ //--------------------------------------------------------------------
	void GCollector::AddChildToRemove(GameObject* child) {
		mToRemoveObjs.insert(child);
	}

	// ------------------------------------------------------------------------
	/*! Add Object To Remove
	*
	*   Removes an object
	*/ //--------------------------------------------------------------------
	void GCollector::AddObjectToRemove(GameObject* obj) {
		mToRemoveObjs.insert(obj);
	}
}